library(caret)
library(plyr)
library(discretization)
library(survival)
source("cvdata.R")
source("ensemble.R")
source("model.R")
source("bin.R")

setwd("C:/Users/Ricky/Desktop")
##2a
train1 <- read.csv(file="acs.csv")
train2 <- read.csv(file="gelg.csv")
train3 <- read.csv(file="ven.csv")
test1 <- read.csv(file="CoreTable_leaderboard_new.csv")
test2 <- read.csv(file="CoreTable_leaderboard_new.csv")
test3 <- read.csv(file="CoreTable_leaderboard_new.csv")
train = rbind(train1,train2,train3)
ctrain = con(train)
dtrain = dic(train)
ctest = con(test1)
dtest = dic(test1)
lbtrain = lab(train,"DEATH")
lbtrain1 = lab(train,"DISCONT")
lbtrain1[is.na(lbtrain1)] <-0
ctrain = cbind(ctrain,lbtrain)
result <- mdlp(ctrain)
ttrain <- ldply (result[2], data.frame)
ttrain= ttrain[,-1]
ttrain$DEATH = NULL
cut <- All_to_Zero(result[1]$cutp)
BT<- mdlp_test(ctest,cut)
ttest  <- ldply (BT[2], data.frame)
ttest = ttest[,-1]
train = cbind(ttrain,dtrain)
test = cbind(ttest,dtest)
train = cbind(train,lbtrain1)
write.csv(train, file = "TrainAll.csv",row.names=FALSE)
write.csv(test, file = "TestAll.csv",row.names=FALSE)
#1a
train1 <- read.csv(file="acs.csv")
train2 <- read.csv(file="gelg.csv")
train3 <- read.csv(file="ven.csv")
test1 <- read.csv(file="CoreTable_leaderboard_new.csv")
test2 <- read.csv(file="CoreTable_leaderboard_new.csv")
test3 <- read.csv(file="CoreTable_leaderboard_new.csv")
  ctrain1<-con(train1)
  ctrain2<-con(train2)
  ctrain3<-con(train3)
  dtrain1<-dic(train1)
  dtrain2<-dic(train2)
  dtrain3<-dic(train3)
  lt1 = lab(train1,"DEATH")
  lt2 = lab(train2,"DEATH")
  lt3 = lab(train3,"DEATH")
  lk1 = lab(train1,"LKADT_P")
  lk2 = lab(train2,"LKADT_P")
  lk3 = lab(train3,"LKADT_P")
  
  ctest1 = con(test1)
  ctest2 = con(test2)
  ctest3 = con(test3)
  dtest1<-dic(test1)
  dtest2<-dic(test2)
  dtest3<-dic(test3)
#binning and feature select to A,B,C
  Btrain<- HowToBin(ctrain1,ctrain2,ctrain3,lt1,lt2,lt3,ctest1,ctest2,ctest3)
  Btrain1 <- ldply (Btrain[1], data.frame)
  Btrain2 <- ldply (Btrain[2], data.frame)
  Btrain3 <- ldply (Btrain[3], data.frame)
  cut1 <- Btrain[4][[1]]
  cut2 <- Btrain[5][[1]]
  cut3 <- Btrain[6][[1]]
  Btest1 <- ldply (Btrain[7], data.frame)
  Btest2 <- ldply (Btrain[8], data.frame)
  Btest3 <- ldply (Btrain[9], data.frame)
  cut1 <- All_to_Zero(cut1)
  cut2 <- All_to_Zero(cut2)
  cut3 <- All_to_Zero(cut3)
  B1<- mdlp_test(Btest1,cut1)
  B2<- mdlp_test(Btest2,cut2)
  B3<- mdlp_test(Btest3,cut3)
  Btest1 <- ldply (B1[2], data.frame)
  Btest2 <- ldply (B2[2], data.frame)
  Btest3 <- ldply (B3[2], data.frame)
  Btest1 = Btest1[,-1]
  Btest2 = Btest2[,-1]
  Btest3 = Btest3[,-1]
  train1 = cbind(Btrain1,dtrain1)
  train2 = cbind(Btrain2,dtrain2)
  train3 = cbind(Btrain3,dtrain3)
  test1 = cbind(Btest1,dtest1)
  test2 = cbind(Btest2,dtest2)
  test3 = cbind(Btest3,dtest3)
  select1 = cbind (lt1,lk1,train1)
  select2 = cbind (lt2,lk2,train2)
  select3 = cbind (lt3,lk3,train3)
  select1$DEATH = as.numeric(lt1$DEATH)
  select2$DEATH = as.numeric(lt2$DEATH)
  select3$DEATH = as.numeric(lt3$DEATH)
  select1$AGEGRP2 = as.numeric(select1$AGEGRP2)
  select2$AGEGRP2 = as.numeric(select2$AGEGRP2)
  select3$AGEGRP2 = as.numeric(select3$AGEGRP2)
  write.csv(select1, file = "Train1.csv",row.names=FALSE)
  write.csv(select2, file = "Train2.csv",row.names=FALSE)
  write.csv(select3, file = "Train3.csv",row.names=FALSE)
  write.csv(test1, file = "Test1.csv",row.names=FALSE)
  write.csv(test2, file = "Test2.csv",row.names=FALSE)
  write.csv(test3, file = "Test3.csv",row.names=FALSE)

